swagger: '2.0'
info:
  version: '1.0.0'
  title: 'Argent Bank Transaction API'
  description: 'API for creating, retrieving, updating and deleting bank transactions'

paths:
  /transactions:
    get:
      summary: 'Get a list of all transactions for the current month'
      responses:
        200:
          description: 'A list of transactions'
        400:
          description: 'Error occurred'
    post:
      summary: 'Add a new transaction'
      responses:
        201:
          description: 'Transaction created successfully'
        400:
          description: 'Error occurred'

  /transactions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Transaction ID
        type: string
    get:
      summary: 'Get the details of a specific transaction'
      responses:
        200:
          description: 'Details of the transaction'
        404:
          description: 'Transaction not found'
    patch:
      summary: 'Update a specific transaction'
      responses:
        200:
          description: 'Transaction updated successfully'
        404:
          description: 'Transaction not found'
    delete:
      summary: 'Remove a specific transaction'
      responses:
        200:
          description: 'Transaction removed successfully'
        404:
          description: 'Transaction not found'
